//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BILL> BILL { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEE { get; set; }
        public virtual DbSet<EMPLOYEE_TYPE> EMPLOYEE_TYPE { get; set; }
        public virtual DbSet<HELP> HELP { get; set; }
        public virtual DbSet<HISTORY> HISTORY { get; set; }
        public virtual DbSet<ITEM> ITEM { get; set; }
        public virtual DbSet<ROOM> ROOM { get; set; }
        public virtual DbSet<ROOM_CUSTOMER> ROOM_CUSTOMER { get; set; }
        public virtual DbSet<ROOM_ORDER> ROOM_ORDER { get; set; }
        public virtual DbSet<ROOM_RESERVE> ROOM_RESERVE { get; set; }
        public virtual DbSet<ROOM_SERVICE> ROOM_SERVICE { get; set; }
        public virtual DbSet<ROOM_TYPE> ROOM_TYPE { get; set; }
        public virtual DbSet<SERVICE> SERVICE { get; set; }
        public virtual DbSet<ROOM_USED> ROOM_USED { get; set; }
    }
}
