//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel_version1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOTEL_EMPLOYEE_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOTEL_EMPLOYEE_TYPE()
        {
            this.HOTEL_EMPLOYEE = new HashSet<HOTEL_EMPLOYEE>();
        }
    
        public string EMP_TYPE { get; set; }
        public Nullable<decimal> SALARY { get; set; }
        public string TYPE_LEVEL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOTEL_EMPLOYEE> HOTEL_EMPLOYEE { get; set; }
    }
}
