//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel_version1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOTEL_EMPLOYEE
    {
        public string EMP_ID { get; set; }
        public string NAME { get; set; }
        public string PHONENUMBER { get; set; }
        public string EMP_TYPE { get; set; }
        public Nullable<decimal> BONUS { get; set; }
    
        public virtual HOTEL_EMPLOYEE_TYPE HOTEL_EMPLOYEE_TYPE { get; set; }
    }
}
