//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel_version1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOTEL_ROOM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOTEL_ROOM()
        {
            this.HOTEL_OCCUPIED = new HashSet<HOTEL_OCCUPIED>();
            this.HOTEL_ORDER = new HashSet<HOTEL_ORDER>();
        }
    
        public string ROOM_TYPE { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public decimal ROOM_NUM { get; set; }
        public string HOTEL_ID { get; set; }
    
        public virtual HOTEL HOTEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOTEL_OCCUPIED> HOTEL_OCCUPIED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOTEL_ORDER> HOTEL_ORDER { get; set; }
    }
}
