//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel_version1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOTEL_CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOTEL_CUSTOMER()
        {
            this.HOTEL_ORDER = new HashSet<HOTEL_ORDER>();
        }
    
        public string CUS_ID { get; set; }
        public string NAME { get; set; }
        public string REPUTATION { get; set; }
        public string TEL_NUMBER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOTEL_ORDER> HOTEL_ORDER { get; set; }
    }
}
