//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel_version1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOTEL_ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOTEL_ORDER()
        {
            this.HOTEL_ITEM_USED = new HashSet<HOTEL_ITEM_USED>();
            this.HOTEL_ORDER_SERVICE = new HashSet<HOTEL_ORDER_SERVICE>();
        }
    
        public string ORDER_ID { get; set; }
        public Nullable<System.DateTime> CHECK_IN_TIME { get; set; }
        public Nullable<System.DateTime> CHECK_OUT_TIME { get; set; }
        public Nullable<System.DateTime> RESERVE_TIME { get; set; }
        public string STATUS { get; set; }
        public string PRE_ORDER_ID { get; set; }
        public string CUS_ID { get; set; }
        public decimal ROOM_NUM { get; set; }
        public string HOTEL_ID { get; set; }
    
        public virtual HOTEL_BILL HOTEL_BILL { get; set; }
        public virtual HOTEL_CUSTOMER HOTEL_CUSTOMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOTEL_ITEM_USED> HOTEL_ITEM_USED { get; set; }
        public virtual HOTEL_ROOM HOTEL_ROOM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOTEL_ORDER_SERVICE> HOTEL_ORDER_SERVICE { get; set; }
    }
}
