//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel_version1._0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HOTEL> HOTELs { get; set; }
        public virtual DbSet<HOTEL_BILL> HOTEL_BILL { get; set; }
        public virtual DbSet<HOTEL_CUSTOMER> HOTEL_CUSTOMER { get; set; }
        public virtual DbSet<HOTEL_EMPLOYEE> HOTEL_EMPLOYEE { get; set; }
        public virtual DbSet<HOTEL_EMPLOYEE_TYPE> HOTEL_EMPLOYEE_TYPE { get; set; }
        public virtual DbSet<HOTEL_ITEM> HOTEL_ITEM { get; set; }
        public virtual DbSet<HOTEL_ITEM_USED> HOTEL_ITEM_USED { get; set; }
        public virtual DbSet<HOTEL_OCCUPIED> HOTEL_OCCUPIED { get; set; }
        public virtual DbSet<HOTEL_ORDER> HOTEL_ORDER { get; set; }
        public virtual DbSet<HOTEL_ROOM> HOTEL_ROOM { get; set; }
        public virtual DbSet<HOTEL_SERVICE> HOTEL_SERVICE { get; set; }
        public virtual DbSet<HOTEL_USER> HOTEL_USER { get; set; }
        public virtual DbSet<HOTEL_ORDER_SERVICE> HOTEL_ORDER_SERVICE { get; set; }
    }
}
